inherit_from: .rubocop_todo.yml

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - '**/*.js'
    - '**/*.css'
    - '**/*.scss'
    - 'public/**/*'

